# Parsing PDFs Homework

With the power of pdfminer, pytesseract, Camelot, and Tika, let's analyze some documents!

> If at any point you think, **"I'm close enough, I'd just edit the rest of it in Excel"**: that's fine! Just make a note of it.

## A trick to use again and again

### Approach 1

Before we get started: when you want to take the first row of your data and set it as the header, use this trick.

In [1]:
import pandas as pd

/Users/isabellachua/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df = pd.DataFrame([
    [ 'fruit name', 'likes' ],
    [ 'apple', 15 ],
    [ 'carrot', 3 ],
    [ 'sweet potato', 45 ],
    [ 'peach', 12 ],
])
df

              0      1
0    fruit name  likes
1         apple     15
2        carrot      3
3  sweet potato     45
4         peach     12

In [3]:
# Set the first row as the columns
df.columns = df.loc[0]

# Drop the first row
df = df.drop(0)

df

0    fruit name likes
1         apple    15
2        carrot     3
3  sweet potato    45
4         peach    12

ðŸš€ Done!

### Approach 2

Another alternative is to use `.rename` on your columns and just filter out the columns you aren't interested in. This can be useful if the column name shows up multiple times in your data for some reason or another.

In [4]:
# Starting with the same-ish data...
df = pd.DataFrame([
    [ 'fruit name', 'likes' ],
    [ 'apple', 15 ],
    [ 'carrot', 3 ],
    [ 'fruit name', 'likes' ],
    [ 'sweet potato', 45 ],
    [ 'peach', 12 ],
])
df

              0      1
0    fruit name  likes
1         apple     15
2        carrot      3
3    fruit name  likes
4  sweet potato     45
5         peach     12

In [5]:
df = df.rename(columns={
    0: 'fruit name',
    1: 'likes'
})
df = df[df['fruit name'] != 'fruit name']
df

     fruit name likes
1         apple    15
2        carrot     3
4  sweet potato    45
5         peach    12

ðŸš€ Done!

### Useful tips about coordinates

If you want to grab only a section of the page [Kull](https://jsoma.github.io/kull/#/) might be helpful in finding the coordinates.

> **Alternatively** run `%matplotlib notebook` in a cell. Afterwards, every time you use something like `camelot.plot(tables[0]).show()` it will get you nice zoomable, hoverable versions that include `x` and `y` coordinates as you move your mouse.

Coordinates are given as `"left_x,top_y,right_x,bottom_y"` with `(0,0)` being in the bottom left-hand corner.

Note that all coordinates are strings, for some reason. It won't be `[1, 2, 3, 4]` it will be `['1,2,3,4']`

# The homework

This is **mostly Camelot work**, because I don't really have any good image-based PDFs to stretch your wings on tesseract. If you know of any, let me know and I can put together another couple exercises.

## Prison Inmates

Working from [InmateList.pdf](InmateList.pdf), save a CSV file that includes every inmate.

* Make sure your rows are *all data*, and you don't have any people named "Inmate Name."

In [6]:
import camelot

In [7]:
tables = camelot.read_pdf("inmate/InmateList.pdf", flavor="stream", pages='1-end')

In [8]:
tables # there are 16 tables in total

In [9]:
tables[0].df

,0,1,2,3,4,5
0,,,,Erie County Sheriff's Office,,
1,,,,Inmate Roster,,
2,ICN #,Inmate Name,,Facility,Booking Date,
3,70693,"ABDALLAH, MICHAEL",,ECHC,04/30/2021,
4,152645,"ABDI, ABDI",,ECCF,06/20/2021,
5,144666,"ABDULLAH, DHAFIR",,ECCF,06/17/2021,
6,156374,"ACEVEDO, CARLOS",,ECHC,06/06/2021,
7,57243,"ACKER, RAYMOND P",,ECCF,11/02/2020,
8,68579,"ADAMS, JERMAIN C",,ECHC,09/19/2019,
9,45262,"ADAMS, MARQUIS",,ECHC,05/27/2021,
10,75738,"AKRIGHT, JOSEPH A",,ECCF,05/29/2021,
11,104048,"ALBERTSON, ANDREW",,ECCF,12/04/2019,
12,1577,"ALEXANDER, BRIAN",,ECHC,07/13/2021,
13,148951,"ALICEA, PABLO E",,ECCF,05/19/2020,
14,139806,"ALKULIFI, ABDULLAH",,ECHC,07/01/2021,
15,124661,"ALLEN, DARNELLE",,ECCF,12/03/2020,
16,125234,"ALLEN, DEMONDE C",,ECHC,05/03/2021,
17,131437,"ALLEN, GLENN A",,ECCF,06/12/2021,
18,144648,"ALLEN, KASSEEN F",,ECHC,06/29/2021,
19,155564,"ALLEN, TIFFANY M",,ECHC,04/12/2021,
20,94012,"AMAN, JOSHUA D",,ECHC,06/27/2021,
21,60170,"ANDREWS, NICOLE J",,ECHC,04/24/2021,
22,1550,"ARCARA, SHAWN",,ECCF,01/20/2021,
23,69158,"ARCHER, MARTELL",,ECHC,07/01/2021,
24,84791,"AULS, RAYMOND",,ECHC,06/03/2021,
25,124759,"AUSTIN, RASHAWN G",,ECHC,01/28/2021,
26,150703,"AYALA, MIKEL D",,ECCF,05/17/2021,
27,90957,"BAEZ, OSCAR J",,ECHC,06/22/2021,
28,144717,"BAILEY, JARELD D",,ECHC,03/18/2021,
29,152772,"BAKER, BRYCE J",,ECCF,12/04/2020,
30,156189,"BALD, EDWARD M",,ECHC,02/27/2021,
31,45844,"BARBER, CORELLIS C",,ECCF,06/02/2021,
32,11444,"BARBER, KEVIN",,ECCF,02/26/2020,
33,99417,"BARCLAY, BRANDON",,ECCF,09/24/2020,
34,121931,"BARCLAY, CHEMERE",,ECHC,04/29/2021,
35,156058,"BARKER, JOHN",,ECHC,11/27/2020,
36,6400,"BARKER, LLOYD",,ECHC,09/30/2020,
37,60960,"BARNES, BYRON K",,ECCF,03/13/2021,
38,143728,"BARNES, DONNELL A",,ECHC,06/30/2021,
39,156210,"BARNWELL, GAIL",,ECHC,03/12/2021,
40,139480,"BARNWELL, RICHARD",,ECCF,10/07/2020,
41,99034,"BARROWMAN, GLENN R",,ECHC,07/08/2021,
42,110974,"BASSETT, BRYAM",,ECHC,05/08/2019,
43,140981,"BASTEDO, ROBARE",,ECCF,02/15/2021,
44,141722,"BATES, MOULIK D",,ECHC,03/16/2021,
45,156050,"BATES, TONY M",,ECHC,04/01/2021,
46,Created On:,"Wednesday, July 14, 2021",At:,9:45:01 am,,Page 1 of 16

In [10]:
import pandas as pd
df = [table.df for table in tables]
df = pd.concat(df, ignore_index=True)

In [11]:
df

,0,1,2,3,4,5
0,,,,Erie County Sheriff's Office,,
1,,,,Inmate Roster,,
2,ICN #,Inmate Name,,Facility,Booking Date,
3,70693,"ABDALLAH, MICHAEL",,ECHC,04/30/2021,
4,152645,"ABDI, ABDI",,ECCF,06/20/2021,
...,...,...,...,...,...,...
742,18303,"ZANGHI, SANTINO J",ECHC,05/24/2021,NaN,NaN
743,155109,"ZARCONE, THOMAS E",ECHC,06/27/2021,NaN,NaN
744,63815,"ZIELINSKI, LARRY",ECHC,07/06/2021,NaN,NaN
745,20740,"ZIELINSKI, LAWRENCE T",ECCF,11/04/2020,NaN,NaN
746,155732,"ZUKIC, TRAVIS",ECCF,03/01/2020,NaN,NaN

In [12]:
# drop the first three rows
df = df.drop([0,1,2])

In [13]:
# rename columns
df = df.rename(columns={
    0: 'ICN #',
    1: 'Inmate Name',
    2: 'Facility',
    3: 'Booking Date',
    4: 'Booking Date',
    5: 'Booking Date'
})
df

,ICN #,Inmate Name,Facility,Booking Date,Booking Date,Booking Date
3,70693,"ABDALLAH, MICHAEL",,ECHC,04/30/2021,
4,152645,"ABDI, ABDI",,ECCF,06/20/2021,
5,144666,"ABDULLAH, DHAFIR",,ECCF,06/17/2021,
6,156374,"ACEVEDO, CARLOS",,ECHC,06/06/2021,
7,57243,"ACKER, RAYMOND P",,ECCF,11/02/2020,
...,...,...,...,...,...,...
742,18303,"ZANGHI, SANTINO J",ECHC,05/24/2021,NaN,NaN
743,155109,"ZARCONE, THOMAS E",ECHC,06/27/2021,NaN,NaN
744,63815,"ZIELINSKI, LARRY",ECHC,07/06/2021,NaN,NaN
745,20740,"ZIELINSKI, LAWRENCE T",ECCF,11/04/2020,NaN,NaN
746,155732,"ZUKIC, TRAVIS",ECCF,03/01/2020,NaN,NaN

In [14]:
inmates = pd.DataFrame(df['Inmate Name'])
inmates

               Inmate Name
3        ABDALLAH, MICHAEL
4               ABDI, ABDI
5         ABDULLAH, DHAFIR
6          ACEVEDO, CARLOS
7         ACKER, RAYMOND P
..                     ...
742      ZANGHI, SANTINO J
743      ZARCONE, THOMAS E
744       ZIELINSKI, LARRY
745  ZIELINSKI, LAWRENCE T
746          ZUKIC, TRAVIS

[744 rows x 1 columns]

In [15]:
# save to csv
inmates.to_csv('inmate_names.csv', index=False)

## WHO resolutions

Using [A74_R13-en.pdf](A74_R13-en.pdf), what ten member countries are given the highest assessments?

* You might need to have two separate queries, and combine the results: that last page is pretty awful!
* Always rename your columns
* Double-check that your sorting looks right......
* You can still get the answer even without perfectly clean data

In [16]:
tables = camelot.read_pdf("who/a74.pdf", flavor="stream", pages="1-end")

In [17]:
dfs = [table.df for table in tables]
dfs = pd.concat(dfs, ignore_index = True)
dfs.sample(20)

                                   0              1    2    3    4
21                             Benin         0.0030  NaN  NaN  NaN
1                  Associate Members  for 2022â€“2023  NaN  NaN  NaN
128                       Montenegro         0.0040  NaN  NaN  NaN
179                  Solomon Islands         0.0010  NaN  NaN  NaN
69                           Finland         0.4210  NaN  NaN  NaN
4                            Albania         0.0080  NaN  NaN  NaN
42                          Colombia         0.2880  NaN  NaN  NaN
157                Republic of Korea         2.2671  NaN  NaN  NaN
195                         Nations)         0.0010  NaN  NaN  NaN
19                           Belgium         0.8211  NaN  NaN  NaN
175                     Sierra Leone         0.0010  NaN  NaN  NaN
68                              Fiji         0.0030  NaN  NaN  NaN
198                          Tunisia         0.0250  NaN  NaN  NaN
75                            Gambia         0.0010  NaN  NaN  NaN
34                        Cabo Verde         0.0010  NaN  NaN  NaN
71                             Gabon         0.0150  NaN  NaN  NaN
43                           Comoros         0.0010  NaN  NaN  NaN
53   Democratic Peopleâ€™s Republic of                 NaN  NaN  NaN
24                       Members and      WHO scale  NaN  NaN  NaN
151                      Philippines         0.2050  NaN  NaN  NaN

In [18]:
dfs = dfs.rename(columns={
    0: 'Country',
    1: 'Score',
})
dfs.sample(30)

,Country,Score,2,3,4
174,Seychelles,0.0020,NaN,NaN,NaN
70,France,4.4273,NaN,NaN,NaN
214,Yemen,0.0100,NaN,NaN,NaN
3,Afghanistan,0.0070,NaN,NaN,NaN
166,San Marino,0.0020,NaN,NaN,NaN
160,Russian Federation,2.4052,NaN,NaN,NaN
120,Associate Members,for 2022â€“2023,NaN,NaN,NaN
168,Associate Members,for 2022â€“2023,NaN,NaN,NaN
2,,%,NaN,NaN,NaN
124,Mexico,1.2921,NaN,NaN,NaN
105,Latvia,0.0470,NaN,NaN,NaN
201,Tuvalu,0.0010,NaN,NaN,NaN
133,Nauru,0.0010,NaN,NaN,NaN
222,,,,,"Seventh plenary meeting, 31 May 2021"
96,Jamaica,0.0080,NaN,NaN,NaN
176,Singapore,0.4850,NaN,NaN,NaN
126,Monaco,0.0110,NaN,NaN,NaN
108,Liberia,0.0010,NaN,NaN,NaN
24,Members and,WHO scale,NaN,NaN,NaN
147,Panama,0.0450,NaN,NaN,NaN
33,Burundi,0.0010,NaN,NaN,NaN
136,New Zealand,0.2910,NaN,NaN,NaN
210,Uzbekistan,0.0320,NaN,NaN,NaN
207,United Republic of Tanzania,0.0100,NaN,NaN,NaN
159,Romania,0.1980,NaN,NaN,NaN
8,Antigua and Barbuda,0.0020,NaN,NaN,NaN
25,Associate Members,for 2022â€“2023,NaN,NaN,NaN
94,Israel,0.4900,NaN,NaN,NaN
22,Bhutan,0.0010,NaN,NaN,NaN
144,Oman,0.1150,NaN,NaN,NaN

In [19]:
df = pd.DataFrame(dfs)
df.groupby('Country')['Score'].sum().sort_values(ascending=False).head(12)

# why doesn't this show China, which has 12%?

Country
Associate Members           for 2022â€“2023for 2022â€“2023for 2022â€“2023for 202...
Members and                     WHO scaleWHO scaleWHO scaleWHO scaleWHO scale
Japan                                                                  8.5645
Germany                                                                6.0904
Northern Ireland                                                       4.5673
France                                                                 4.4273
Italy                                                                  3.3072
United States of America                                              22.0000
Brazil                                                                 2.9482
Canada                                                                 2.7342
Russian Federation                                                     2.4052
Republic of Korea                                                      2.2671
Name: Score, dtype: object

## The Avengers

Using [THE_AVENGERS.pdf](THE_AVENGERS.pdf), approximately how many lines does Captain America have as compared to Thor and Iron Man?

* Character names only: we're only counting `IRON MAN` as Iron Man, not `TONY`.
* Your new best friend might be `\n`
* Look up `.count` for strings

In [20]:
import tika
from tika import parser

In [21]:
parsed = parser.from_file('avengers/script.pdf')

2021-07-21 15:21:31,029 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.24/tika-server-1.24.jar to /var/folders/vc/7_xzcn5x33s8_1z79755hp6m0000gn/T/tika-server.jar.
2021-07-21 15:22:17,445 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.24/tika-server-1.24.jar.md5 to /var/folders/vc/7_xzcn5x33s8_1z79755hp6m0000gn/T/tika-server.jar.md5.
2021-07-21 15:22:19,749 [MainThread  ] [WARNI]  Failed to see startup log message; retrying...

In [22]:
parsed['content'].strip()

'Marvelâ€™s THE AVENGERS\n\nWritten By\n\nJoss Whedon\n\nStory By\n\nZak Penn and Joss Whedon\n\nBased on the characters appearing in the comic books\n\nPublished by MARVEL Comics\n\nTranscribed to PDF using:\n\nCeltx Studio | 2012\n\nComposed In Celtx Studio\n\nWith the help of\n\nSiOmniaFictaâ€™s Script\n\non fanfiction.net\n\nENTERTAINMENT PURPOSES ONLY\n\n\n\n1 EXT. UNKNOWN AREA OF SPACE 1\n\nSpace, a floating staircase among the rocks...THE OTHER\n\nspeaks to a DISEMBODIED FIGURE in a chair.\n\nTHE OTHER (V.O)\n\nThe Tesseract has awakened. It is\n\non a little world, a human world.\n\nThey would wield its power.\n\nTHE OTHER hands LOKI a scepter with a glowing blue gem...\n\nTHE OTHER (V.O)\n\nBut our ally knows its workings as\n\nthey never will. He is ready to\n\nlead. And our force...\n\nThe CHITAURI put on their face mask and get ready.\n\nTHE OTHER (V.O)\n\n...our Chitauri, will follow. The\n\nworld will be his...the universe,\n\nyours. And the humans, what can\n\nthey do but burn?\n\nA 3d model of the Tesseract, we move inside it slowly\n\n2 EXT. MOUNTAIN RANGE - EARLY NIGHT 2\n\nA helicopter SPEEDS over this mountain at high-speed. The\n\nCAMERA pans up over the mountain and we see...\n\n3 EXT. SHIELD/NASA FACILITY - CONTINUOUS 3\n\nThis base is grand beyond belief. There is a frantic\n\nevacuation in progress. AGENTS, SCIENTISTS, and PERSONNEL\n\nrush around the base frantically.\n\nINTERCOM VOICE\n\nAll personnel, evacuation order has\n\nbeen confirmed. Proceed to your\n\ndesignated vehicles...\n\nA man flushes people by. The sign on the building reads:\n\nJOINT DARK ENERGY MISSION; WESTERN DIVISION; PROJECT\n\nPEGASUS, NASA SPACE RADIATION FACILITY, S.H.I.E.L.D\n\nACCELERATOR TEST FACILITY\n\nINTERCOM VOICE\n\n...for all campus evacuation.\n\nSecurity Guards direct traffic. SHIELD agents assist people,\n\nsome stuff the trunks of their cars and leave the campus.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 2.\n\nINTERCOM VOICE (CONTâ€™D)\n\nThis is not a drill. Emergency\n\npersonnel proceed to your\n\ndesignated vehicles for all campus\n\nevacuation.\n\nThe helicopter slows above a-\n\n4 EXT. LANDING PAD, SHIELD/NASA FACILITY - CONTINUOUS 4\n\nThere is a man in suit waiting. This is AGENT PHIL COULSON.\n\nON THE CHOPPER: The door slides open. Out comes a female,\n\nthis is AGENT MARIA HILL. Following behind her is NICK FURY.\n\nFury and Hill walk over to Coulson.\n\nFURY\n\nHow bad is it?\n\nAGENT COULSON\n\nThatâ€™s the problem, sir. We donâ€™t\n\nknow.\n\n5 INT. ELEVATOR SHAFT - MOMENTS LATER (EARLY NIGHT) 5\n\nAn elevator rushes down. Itâ€™s going fast.\n\nAGENT COULSON (V.O)\n\nDoctor Selvig read an...\n\n6 INT. LOWER LEVEL - CONTINUOUS 6\n\nCoulson, Fury, and Hill make their way through the crowds of\n\nevacuating personnel.\n\nAGENT COULSON\n\n...energy surge from the Tesseract\n\nfour hours ago.\n\nFURY\n\nNASA didnâ€™t authorize Selvig could\n\ngo to test B.\n\nAGENT COULSON\n\nHe wasnâ€™t testing it. He wasnâ€™t\n\neven in the room. Spontaneous\n\nevent.\n\nMARIA HILL\n\nIt just turned itself on?\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 3.\n\nFURY\n\nWhere are the energy levels now?\n\nAGENT COULSON\n\nClimbing. When Selvig couldnâ€™t shut\n\nit down we ordered evac.\n\nFURY\n\nHow long to get everyone out?\n\nAGENT COULSON\n\nCampus should be clear in the next\n\nhalf hour.\n\nFURY\n\nDo better.\n\nFury and Hill continue on as Coulson turns around and heads\n\nthe other way.\n\n7 INT. STAIRCASE - MOMENTS LATER (EARLY NIGHT) 7\n\nFury and Hill make their way down to the lower levels.\n\nMARIA HILL\n\nSir, evacuation may be futile.\n\nFURY\n\nWe should tell them to go back to\n\nsleep?\n\nMARIA HILL\n\nIf we canâ€™t control the Tesseractâ€™s\n\nenergy there may not be a minimum\n\nsafe distance.\n\nFURY\n\nI need you to make sure the Phase\n\nTwo prototypes are shipped out.\n\nMARIA HILL\n\nSir, is that really a priority\n\nright now?\n\nFURY\n\nUntil such time as the world ends\n\nwe will act as though it intends to\n\nspin on. Clear out the tech below.\n\nEvery piece of Phase Two on a truck\n\nand gone.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 4.\n\nMARIA HILL\n\nYes, Sir.\n\n(to guards)\n\nWith me.\n\nFury enters the Tesseract room.\n\n8 INT. TESSERACT CHAMBER ROOM - CONTINUOUS (EARLY NIGHT) 8\n\nFury makes his way over to ERIK SELVIG.\n\nFURY\n\nTalk to me, Doctor.\n\nSELVIG\n\nDirector.\n\nFURY\n\nIs there anything we know for\n\ncertain?\n\nSELVIG\n\nThe Tesseract is misbehaving.\n\nFURY\n\nIs that supposed to be funny?\n\nSELVIG\n\nNo, itâ€™s not funny at all. The\n\nTesseract is not only active, sheâ€™s\n\nmisbehaving.\n\nFURY\n\nHow soon can you pull the plug?\n\nSELVIG\n\nSheâ€™s an energy source. We turn off\n\nthe power, she turns it back on. If\n\nshe reaches peak level-\n\nFURY\n\nWe prepared for this, Doctor.\n\nHarnessing energy from space.\n\nSELVIG\n\nWe donâ€™t have the harness. My\n\ncalculations are far from complete.\n\nSheâ€™s throwing off interference,\n\nradiation. Nothing harmful, low\n\nlevels of Gamma radiation.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 5.\n\nFURY\n\nThat can be harmful. Whereâ€™s agent\n\nBarton?\n\nSELVIG\n\nThe hawk? Up in his nest, as usual.\n\nCLINT BARTON, also known as HAWKEYE, is on a balcony,\n\nobserving the lab.\n\nFURY\n\n(over Bartonâ€™s radio)\n\nAgent Barton. Report.\n\nBarton zip-lines down a rope.\n\nFURY (V.O)\n\n(sturn)\n\nI gave you this detail so you could\n\nkeep a close eye on things.\n\nFury and Barton walk together toward the Tesseract machine.\n\nBARTON\n\nI see better from a distance.\n\nFURY\n\nHave you seen anything that might\n\nset this thing off?\n\nA NASA SCIENTIST calls for Selvig.\n\nNASA SCIENTIST\n\nDoctor! Itâ€™s spiking again.\n\nBarton and Fury step onto the platform, in front of the\n\nTesseract machine.\n\nBARTON\n\nNo oneâ€™s come and gone. And\n\nSelvigâ€™s clean. No contacts, no IM.\n\nIf thereâ€™s any tampering, sir, it\n\nwasnâ€™t this end.\n\nWhile Barton is talking Selvig walks over to the computer\n\nwhere the NASA SCIENTIST is. He looks concerned and worried.\n\nFURY\n\n(a little confused)\n\nAt this end?\n\n(CONTINUED)\n\n\n\nCONTINUED: (3) 6.\n\nBARTON\n\nYeah. The Cube is a doorway to the\n\nother end of space, right? Doors\n\nopen from both sides.\n\nThe Cube sparks.\n\nSELVIG\n\nWhatâ€™s that?\n\nIt sparks again.\n\n9 EXT. BEHIND A TRUCK - SAME (EARLY NIGHT) 9\n\nCoulson stands. The grounds of the campus shakes. He grabs\n\nthe truck.\n\n10 INT. SECURITY LEVEL FOUR - SAME 10\n\nHill turns and looks around her, hearing a creaking noise as\n\nthe building shakes.\n\n11 INT. TESSERACT CHAMBER ROOM - CONTINUOUS 11\n\nThe Cube sparks some more, bigger each time. A beam of\n\nenergy which opens into a portal. There is an explosion.\n\nA could from the beam floats to the top of the chamber. On\n\nthe platform is LOKI, God of Mischief and Lies, kneeling.\n\nSeveral GUARDS move in slowly.\n\nTIGHT ON LOKI: He looks up, grinning menacingly. She stands.\n\nDOLLY IN: Fury and Barton stare in shock.\n\nON SELVIG: He is in awe and horror.\n\nLoki looks around. Fury is ready to act.\n\nFURY\n\n(to Loki)\n\nSir, please put down the spear!\n\nLoki looks at his scepter then fires a stream on blue light\n\nfrom it. Barton pushes Fury out the way. The guards open\n\nfire. Loki jumps at them, firing more energy and fighting.\n\nShooting scientists and agents. Barton moves towards him but\n\nLoki grabs his arm.\n\nLOKI\n\nYou have heart.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 7.\n\nLoki touches the tip of the spear to Bartonâ€™s chest and his\n\neyes become ice blue. He puts his gun away. Loki moves to\n\nanother agent and does the same as heâ€™s done to Barton.\n\nFury pulls the Cube from the machine it was in and shuts it\n\nin a briefcase, then moves to leave.\n\nLOKI\n\n(to Fury, turning around)\n\nPlease donâ€™t. I still need that.\n\nFURY\n\nThis doesnâ€™t have to get any\n\nmessier.\n\nLOKI\n\nOf course it does. Iâ€™ve come too\n\nfar for anything else. I am Loki,\n\nof Asgard. And I am burdened with\n\nglorious purpose.\n\nSelvig, checking the pulse of NASA SCIENTIST, hears and\n\napproaches.\n\nSELVIG\n\nLoki, brother of Thor?\n\nFURY\n\nWe have no quarrel with your\n\npeople.\n\nLOKI\n\nAn ant has no quarrel with a boot.\n\nFURY\n\nYou planning to step on us?\n\nLOKI\n\nI come with glad tidings, of a\n\nworld made free.\n\nFURY\n\nFree from what?\n\nLOKI\n\nFreedom. Freedom is lifeâ€™s great\n\nlie. Once you accept that, in your\n\nheart-\n\nLoki turns and places the spear tip on Selvigâ€™s chest.\n\n-you will know peace.\n\nBarton sees the Tesseract portal cloud, brewing and moves to\n\nLoki.\n\n(CONTINUED)\n\n\n\nCONTINUED: (3) 8.\n\nFURY\n\nYeah, you say peace. I kinda think\n\nyou mean the other thing.\n\nBARTON\n\n(to Loki)\n\nSir, Director Fury is stalling.\n\nThis place is about to blow and\n\ndrop a hundred feet of rock on us.\n\nHe means to bury us.\n\nFURY\n\nLike the pharaohs of old.\n\nSELVIG\n\nHeâ€™s right. The portal is\n\ncollapsing in on itself. Weâ€™ve got\n\nmaybe two minutes before this goes\n\ncritical.\n\nLOKI\n\nWell then.\n\nBarton quickly draws his gun and shoots Fury, who drops the\n\ncase. Barton picks up as he, Loki, Selvig and another agent\n\nleave the room.\n\n12 INT. SECURITY LEVEL FOUR - A FEW SHORT MOMENTS LATER 12\n\nBarton and the others walk under the closing gate. Hill\n\ncomes out from the back room.\n\nBARTON\n\nWe need this vehicles.\n\nMARIA HILL\n\n(seeing Loki)\n\nWhoâ€™s that?\n\nBARTON\n\nDidnâ€™t tell me.\n\nThe roof is slowly crumbling. Loki gets onto a SHIELD pickup\n\ntruck. Selvig enters the passenger seat, holding the case.\n\nFURY\n\n(over Hillâ€™s radio)\n\nHill!\n\n\n\n9.\n\n13 INT. TESSERACT CHAMBER ROOM - CONTINUOUS 13\n\nFURY\n\n(into his radio)\n\nDo you copy?\n\n14 INT. SECURITY LEVEL FOUR - CONTINUOUS 14\n\nFURY\n\n(over Hillâ€™s radio)\n\nBarton...has turned.\n\nBarton pulls his gun and fires at Hill, who rolls behind the\n\nback room wall and returns fire. Barton enters the driverâ€™s\n\nseat of the pickup and drives off with Loki is in the bed.\n\n15 INT. TESSERACT CHAMBER ROOM - CONTINUOUS 15\n\nFury stands up and rushes out as the Tesseract cloud gets\n\nbigger and bigger above him. The lab is getting destroyed.\n\nFURY\n\n(into radio)\n\nGet the Tesseract. Shut them down.\n\n16 INT. SECURITY LEVEL FOUR - CONTINUOUS 16\n\nHill throws her radio into the front seat of a SHIELD jeep.\n\nShe jumps in after and speeds away, trying to catch up with\n\nBarton.\n\n17 INT. DIMLY LIT UNDERGROUND TUNNEL - CONTINUOUS 17\n\nSHIELD cars are chasing Bartonâ€™s pickup. Loki fires a beam\n\nfrom his spear, flipping the car over on its head --\n\nblocking the pursuing vehicles and fleeing cars.\n\n18 INT. LOWER LEVEL - CONTINUOUS (EARLY DAWN) 18\n\nThe portal begins to collapse as Fury tries to escape.\n\nFalling debris misses him by a few inches.\n\n19 INT. FRONT STEPS OF A BUILDING - CONTINUOUS 19\n\nCoulson is assisting evacuation, supervising guards as the\n\nwheel crates. An explosion rocks the building. They all fall\n\nas the roof dissolves faster. The four guards try to pick up\n\nthe case-\n\nAGENT COULSON\n\n(to guards)\n\nLetâ€™s just go. No-no-no! Leave it,\n\nleave it. GO!\n\n\n\n10.\n\n20 INT. DIMLY LIT UNDERGROUND TUNNEL - CONTINUOUS 20\n\nBarton speeds up because heâ€™s coming up on an intersection.\n\nHill comes speeding out of the right tunnel, she spins the\n\njeep around -- coming face to face with Barton, who shoots\n\nthrough his window. Hill returns fire -- firing through the\n\nwindshield.\n\n21 INT. MILITARY TRANSPORT TRUCK - CONTINUOUS 21\n\nCoulson and the guards climb into the canopy of the truck.\n\nAGENT COULSON\n\n(into radio)\n\nWeâ€™re clear upstairs, sir...\n\n22 EXT. LANDING PAD, SHIELD/NASA FACILITY - CONTINUOUS 22\n\nFury runs through the front door of a building and into...\n\nAGENT COULSON (V.O)\n\n(over Furyâ€™s radio)\n\n...We need to go.\n\nThe last waiting chopper, which takes off as the ground\n\nbeneath begins to crack up.\n\n23 INT. DIMLY LIT UNDERGROUND TUNNEL - CONTINUOUS 23\n\nBarton fires at Hill one more time. She fires back, finally\n\nBarton gets the upper hand and swings in front of Hill --\n\ncutting her off. She turns he jeep around and continues to\n\nspeed behind them.\n\n24 EXT. LANDING PAD, SHIELD/NASA FACILITY - CONTINUOUS 24\n\nFuryâ€™s chopper is in the air, the ground begins collapsing.\n\n25 INT. TESSERACT CHAMBER ROOM - CONTINUOUS 25\n\nThe Tesseract portal cloud explodes.\n\n26 EXT. SHIELD/NASA FACILITY - CONTINUOUS 26\n\nThe entire base explodes and crumbles in on itself --\n\nsinking into the underground. Fury watches in horror from\n\nhis chopper window.\n\n\n\n11.\n\n27 DIMLY LIT UNDERGROUND TUNNEL - CONTINUOUS 27\n\nThe ceiling of the tunnel falls, trapping Hill and other\n\nagents underground. Loki looks at the exit to see if they\n\nwill make it out.\n\n28 INT. MILITARY TRANSPORT TRUCK - CONTINUOUS 28\n\nCoulson and the others in the canopy stare at the ground\n\nbehind their truck -- the ground is still collapsing,\n\nseconds behind there vehicle, they get away in time.\n\n29 EXT. DESERT - CONTINUOUS (NIGHT) 29\n\nLoki and the others escape the tunnel seconds before the\n\nexit is covered up by the fallen ceiling. As they drive\n\nalong, Furyâ€™s chopper chases them. Barton drives frantically\n\nas Fury shoots at them from the sky.\n\nLoki blasts the helicopter and Fury jumps to the ground as\n\nit crashes, he continues to fire as the truck drives off in\n\nthe distance. He stands.\n\nAGENT COULSON\n\n(over Furyâ€™s radio)\n\nDirector.\n\nBEGIN INTERCUT: FURY / TRUCK CANOPY / UNDERGROUND TUNNEL\n\nAGENT COULSON (CONTâ€™D)\n\n(into radio)\n\nDirector Fury, do you copy?\n\nFURY\n\n(into radio)\n\nThe Tesseract is with a hostile\n\nforce. I have men down. Hill?\n\nMARIA HILL\n\n(into radio; getting out of\n\ncrushed jeep)\n\nA lot of men still under. Donâ€™t\n\nknow how many survivors.\n\nFURY\n\n(over Hillâ€™s radio)\n\nSound a general call. I want every\n\nliving soul...\n\nFURY\n\n(into radio)\n\n...not working rescue looking for\n\nthat briefcase.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 12.\n\nMARIA HILL\n\n(into radio)\n\nRoger that.\n\nFURY\n\n(into radio)\n\nCoulson, get back to base.\n\nFURY\n\n(over Coulsonâ€™s radio)\n\nThis is a level seven.\n\nFURY\n\n(over Hillâ€™s radio)\n\nAs of right now...\n\nFURY\n\n(into his radio)\n\nWe are at war.\n\nAGENT COULSON\n\n(into his radio)\n\nWhat do we do?\n\nFury thinks, as the CAMERA GOES TIGHT on him.\n\nTITLE CARD: Marvelâ€™s THE AVENGERS\n\n30 EXT. OLD WAREHOUSE, RUSSIA - NIGHT 30\n\nA train speeds by. CAMERA PULLS through the warehouse window\n\nand MOVES UP to the third floor where NATASHA ROMANOFF aka\n\nBLACK WIDOW, is tied to a chair. A man slaps her. She\n\nscreams.\n\nGEORGI LUCHKOV\n\n(in Russian)\n\nThis isnâ€™t how I wanted this\n\nevening to go.\n\nNATASHA\n\n(in Russian)\n\nI know how you wanted this evening.\n\nBelieve me this is better.\n\nGEORGI LUCHKOV\n\n(in Russian)\n\nWho are you working for? Lermentov,\n\nyes?\n\nTALL THUG walks over to Natasha and leans the chair over a\n\npit. She becomes scared.\n\n(CONTINUED)\n\n\n\nCONTINUED: (2) 13.\n\nGEORGI LUCHKOV (CONTâ€™D)\n\n(in Russian)\n\nDoes he think we have to go through\n\nhim to move our cargo?\n\nNATASHA\n\n(in Russian)\n\nI thought General Solohob is in\n\ncharge of the export business.\n\nGEORGI LUCHKOV\n\n(in Russian)\n\nSolohob. A bagman, a front. Your\n\noutdated information betrays you.\n\nThe famous Black Widow is just\n\nanother pretty face.\n\nNATASHA\n\n(in Russian)\n\nYou really think Iâ€™m pretty?\n\nTALL THUG grabs her jaw and forces it open as Luchkov walks\n\nto the table behind him.\n\nGEORGI LUCHKOV\n\n(in Russian)\n\nTell Lermentov we donâ€™t need him to\n\nmove the tanks. Tell him he is out.\n\nWell...\n\nLuchkov picks up a tool of the table and plays with it.\n\n...You may have to write it.\n\nSuddenly a phone rings. WEASELLY THUG answers his phone.\n\nWEASELLY THUG\n\nItâ€™s for her.\n\nLuchkov takes the phone.\n\nGEORGI LUCHKOV\n\n(in Russian; into cell)\n\nYou listen carefully-\n\nAGENT COULSON (V.O)\n\n(over the cell)\n\nYouâ€™re at 1- 14 Silensky Plaza, 3rd\n\nfloor. We have an F-22 exactly\n\neight miles out. Put the woman on\n\nthe phone or I will blow up the\n\nblock before you can make the\n\nlobby.\n\n(CONTINUED)\n\n\n\nCONTINUED: (3) 14.\n\nLuchkov hands the phone to Natasha, who balances it on her\n\nshoulder.\n\n(over the cell)\n\nWe need you to come in.\n\nNATASHA\n\n(into cell)\n\nAre you kidding? Iâ€™m working.\n\nAGENT COULSON\n\n(over the cell)\n\nThis takes precedence.\n\nNATASHA\n\n(into cell)\n\nIâ€™m in the middle of an\n\ninterrogation, and this moron is\n\ngiving me everything.\n\nGEORGI LUCHKOV\n\n(to Tall Thug)\n\nI not- give everything.\n\nNatasha gives Luchkov a look.\n\nBEGIN INTERCUT: COULSON / NATASHA\n\nNATASHA\n\n(into cell)\n\nLook, you canâ€™t pull me out of this\n\nright now.\n\nAGENT COULSON\n\n(into cell)\n\nNatasha...Bartonâ€™s been\n\ncompromised.\n\nNATASHA\n\n(into cell)\n\nLet me put you on hold.\n\nLuchkov moves in for the cell phone. Natasha kicks him\n\nbetween the legs and headbutts him. WEASELLY THUG swings his\n\nfist at her and she kicks him back. TALL THUG runs up and\n\nshe spins around -- and the chair legs hit him.\n\nWEASELLY THUG jumps to his feet. Natasha rolls with the\n\nchair and drops the legs on his feet. She whips her head at\n\nhim and hits him in the nose then trips him.\n\nAs she fights the TALL THUG, Coulson listens to the fight\n\nover the phone. He stands quiet -- waiting as he hears the\n\ngroaning, kicking, and punching.\n\n(CONTINUED)\n\n\n\nCONTINUED: (4) 15.\n\nNatasha spring boards off TALL THUGâ€™s back, somersaults, and\n\nbreaks the chair on WEASELLY THUG. TALL THUG grabs her and\n\nNatasha bends his hand then hits him with the chair leg. She\n\ndoes a front dropkick against TALL THUG then pushes herself\n\noff the ground with both hands.\n\nShe runs toward TALL THUG, who is out of breath, and flips\n\nhim with her thighs. Luchkov stands and she swiftly walks\n\nover to the chain hanging from the ceiling. As he approaches\n\nshe hits him with it, wraps one leg in it, and throws him\n\ninto the pit. She leaves him upside down and picks up the\n\ncell and her high heels.\n\nNATASHA (CONTâ€™D)\n\n(into cell)\n\nWhereâ€™s Barton now?\n\nAGENT COULSON\n\n(over cell)\n\nWe donâ€™t know.\n\nNATASHA\n\nBut heâ€™s alive?\n\nAGENT COULSON\n\n(into phone)\n\nWe think so.\n\nCoulson is looking at a screen thatâ€™s playing a video of\n\nHawkeye & Black Widow in Budapest.\n\nWeâ€™ll brief you on everything when\n\nyou get back.\n\nCoulson is handed a folder. He walks down some stairs as he\n\ntalks.\n\nBut first, we need you to talk to\n\nthe big guy.\n\nNATASHA\n\n(into cell)\n\nCoulson, you know that Stark trusts\n\nme about as far as he can throw me.\n\nAGENT COULSON\n\nOh Iâ€™ve got Stark! You get the big\n\nguy.\n\nEND INTERCUT\n\nNatasha stops in her tracks, shocked at what Coulson has\n\njust said.\n\n(CONTINUED)\n\n\n\nCONTINUED: (5) 16.\n\nNATASHA\n\n(in Russian; quietly)\n\nMy God.\n\n31 EXT. SLUMS, CALCUTTA, INDIA - NIGHT 31\n\nA YOUNG GIRL sprints across a busy street. She runs through\n\na crowd of people, rushing down an busy alleyway. She runs\n\ninto a house and up the stairs.\n\nCALCUTTA WOMAN approaches her. BRUCE BANNER, the alter ego\n\nof the Incredible Hulk, is treating the ill in the b.g.\n\nCALCUTTA WOMAN\n\n(in Hindi)\n\nWho are you? Get out! There is\n\nsickness here!\n\nYOUNG GIRL\n\n(very fast in Hindi)\n\nAre you the doctor? I need a\n\ndoctor. My father. My fatherâ€™s not\n\nwaking up! He has a fever and heâ€™s\n\nmoaning but his eyes wonâ€™t open.\n\nBanner hears and moves over to the YOUNG GIRL. He kneels\n\nbefore her.\n\nBANNER\n\n(in Hindi)\n\nSlow down.\n\nYOUNG GIRL\n\n(in Hindi)\n\nMy father-\n\nBANNER\n\n(in Hindi)\n\nLike them?\n\nBanner points to the people in

In [23]:
iron_man = parsed['content'].count('\nIRON MAN\n')
iron_man

19

In [24]:
cap = parsed['content'].count('\nCAPTAIN AMERICA\n')
cap

35

In [25]:
thor = parsed['content'].count('\nTHOR\n')
thor

47

## COVID data

Using [covidweekly2721.pdf](covidweekly2721.pdf), what's the total number of tests performed in Minnesota? Use the Laboratory Test Rates by County of Residence chart.

* You COULD pull both tables separately OR you could pull them both at once and split them in pandas.
* Remember you can do things like `df[['name','age']]` to ask for multiple columns

In [26]:
tables = camelot.read_pdf("covid/covid_weekly.pdf", flavor="lattice", pages='6')
tables[1].df

,0,1,2,3,4,5
0,County,Number of Tests,Cumulative Rate,County,Number of Tests,Cumulative Rate
1,Aitkin,"19,204","12,128",Martin,"39,876","19,974"
2,Anoka,"545,958","15,714",McLeod,"61,300","17,111"
3,Becker,"59,238","17,540",Meeker,"37,736","16,351"
4,Beltrami,"60,345","13,085",Mille Lacs,"44,688","17,369"
5,Benton,"77,865\n9,953","26,976",Morrison,"59,179","17,961"
6,Big Stone,"13,220","26,356",Mower,"79,446","20,061"
7,Blue Earth,"136,895","20,641",Murray,"15,175","18,167"
8,Brown,"55,709","22,097",Nicollet,"66,163","19,585"
9,Carlton,"79,882","22,477",Nobles,"30,979","14,185"
10,Carver,"154,305","15,367",Norman,"11,471","17,489"
11,Cass,"31,760","10,943",Olmsted,"277,493","18,129"
12,Chippewa,"27,089","22,555",Otter Tail,"110,163","18,996"
13,Chisago,"90,811","16,593",Pennington,"15,424","10,874"
14,Clay,"108,867","17,335",Pine,"35,859","12,310"
15,Clearwater,"9,427","10,698",Pipestone,"19,655","21,399"
16,Cook,"8,966","16,882",Polk,"42,729","13,526"
17,Cottonwood,"21,088","18,544",Pope,"20,459","18,633"
18,Crow Wing,"85,522","13,393",Ramsey,"987,792","18,242"
19,Dakota,"715,290","17,104",Red Lake,"4,078","10,175"
20,Dodge,"37,729","18,331",Redwood,"27,476","17,922"
21,Douglas,"68,086","18,301",Renville,"30,498","20,717"
22,Faribault,"31,294","22,520",Rice,"177,409","26,976"
23,Fillmore,"40,081","19,189",Rock,"19,147","20,341"
24,Freeborn,"63,008","20,641",Roseau,"23,169","14,984"
25,Goodhue,"87,119","18,850",Scott,"230,375","16,068"
26,Grant,"10,310","17,363",Sherburne,"184,952","19,838"
27,Hennepin,"2,292,159","18,553",Sibley,"24,133","16,184"
28,Houston,"21,417","11,476",St. Louis,"383,063","19,145"
29,Hubbard,"20,764","9,953",Stearns,"285,098","18,180"
30,Isanti,"56,067","14,386",Steele,"64,840","17,679"
31,Itasca,"80,265","17,757",Stevens,"20,325","20,774"
32,Jackson,"14,075","14,009",Swift,"18,288","19,433"
33,Kanabec,"16,504","10,312",Todd,"33,013","13,508"
34,Kandiyohi,"85,305","19,997",Traverse,"7,041","21,100"
35,Kittson,"9,969","22,986",Wabasha,"46,421","21,591"
36,Koochiching,"21,647","17,120",Wadena,"33,447","24,510"
37,Lac qui Parle,"13,601","20,081",Waseca,"34,795","18,499"
38,Lake,"19,664","18,605",Washington,"460,537","18,180"
39,Lake of the Woods,"5,957","15,639",Watonwan,"20,172","18,383"
40,Le Sueur,"43,972","15,714",Wilkin,"7,973","12,570"
41,Lincoln,"10,696","18,742",Winona,"106,625","20,970"
42,Lyon,"46,116","17,847",Wright,"194,085","14,621"
43,Mahnomen,"6,643","12,065",Yellow Medicine,"19,972","20,239"
44,Marshall,"10,279","10,944",Unknown/missing,"423,136",

In [27]:
df = pd.DataFrame(tables[1].df)
df

,0,1,2,3,4,5
0,County,Number of Tests,Cumulative Rate,County,Number of Tests,Cumulative Rate
1,Aitkin,"19,204","12,128",Martin,"39,876","19,974"
2,Anoka,"545,958","15,714",McLeod,"61,300","17,111"
3,Becker,"59,238","17,540",Meeker,"37,736","16,351"
4,Beltrami,"60,345","13,085",Mille Lacs,"44,688","17,369"
5,Benton,"77,865\n9,953","26,976",Morrison,"59,179","17,961"
6,Big Stone,"13,220","26,356",Mower,"79,446","20,061"
7,Blue Earth,"136,895","20,641",Murray,"15,175","18,167"
8,Brown,"55,709","22,097",Nicollet,"66,163","19,585"
9,Carlton,"79,882","22,477",Nobles,"30,979","14,185"
10,Carver,"154,305","15,367",Norman,"11,471","17,489"
11,Cass,"31,760","10,943",Olmsted,"277,493","18,129"
12,Chippewa,"27,089","22,555",Otter Tail,"110,163","18,996"
13,Chisago,"90,811","16,593",Pennington,"15,424","10,874"
14,Clay,"108,867","17,335",Pine,"35,859","12,310"
15,Clearwater,"9,427","10,698",Pipestone,"19,655","21,399"
16,Cook,"8,966","16,882",Polk,"42,729","13,526"
17,Cottonwood,"21,088","18,544",Pope,"20,459","18,633"
18,Crow Wing,"85,522","13,393",Ramsey,"987,792","18,242"
19,Dakota,"715,290","17,104",Red Lake,"4,078","10,175"
20,Dodge,"37,729","18,331",Redwood,"27,476","17,922"
21,Douglas,"68,086","18,301",Renville,"30,498","20,717"
22,Faribault,"31,294","22,520",Rice,"177,409","26,976"
23,Fillmore,"40,081","19,189",Rock,"19,147","20,341"
24,Freeborn,"63,008","20,641",Roseau,"23,169","14,984"
25,Goodhue,"87,119","18,850",Scott,"230,375","16,068"
26,Grant,"10,310","17,363",Sherburne,"184,952","19,838"
27,Hennepin,"2,292,159","18,553",Sibley,"24,133","16,184"
28,Houston,"21,417","11,476",St. Louis,"383,063","19,145"
29,Hubbard,"20,764","9,953",Stearns,"285,098","18,180"
30,Isanti,"56,067","14,386",Steele,"64,840","17,679"
31,Itasca,"80,265","17,757",Stevens,"20,325","20,774"
32,Jackson,"14,075","14,009",Swift,"18,288","19,433"
33,Kanabec,"16,504","10,312",Todd,"33,013","13,508"
34,Kandiyohi,"85,305","19,997",Traverse,"7,041","21,100"
35,Kittson,"9,969","22,986",Wabasha,"46,421","21,591"
36,Koochiching,"21,647","17,120",Wadena,"33,447","24,510"
37,Lac qui Parle,"13,601","20,081",Waseca,"34,795","18,499"
38,Lake,"19,664","18,605",Washington,"460,537","18,180"
39,Lake of the Woods,"5,957","15,639",Watonwan,"20,172","18,383"
40,Le Sueur,"43,972","15,714",Wilkin,"7,973","12,570"
41,Lincoln,"10,696","18,742",Winona,"106,625","20,970"
42,Lyon,"46,116","17,847",Wright,"194,085","14,621"
43,Mahnomen,"6,643","12,065",Yellow Medicine,"19,972","20,239"
44,Marshall,"10,279","10,944",Unknown/missing,"423,136",

In [28]:
df.columns = df.loc[0]

In [29]:
df = df.drop(0)
df

,County,Number of Tests,Cumulative Rate,County,Number of Tests,Cumulative Rate
1,Aitkin,"19,204","12,128",Martin,"39,876","19,974"
2,Anoka,"545,958","15,714",McLeod,"61,300","17,111"
3,Becker,"59,238","17,540",Meeker,"37,736","16,351"
4,Beltrami,"60,345","13,085",Mille Lacs,"44,688","17,369"
5,Benton,"77,865\n9,953","26,976",Morrison,"59,179","17,961"
6,Big Stone,"13,220","26,356",Mower,"79,446","20,061"
7,Blue Earth,"136,895","20,641",Murray,"15,175","18,167"
8,Brown,"55,709","22,097",Nicollet,"66,163","19,585"
9,Carlton,"79,882","22,477",Nobles,"30,979","14,185"
10,Carver,"154,305","15,367",Norman,"11,471","17,489"
11,Cass,"31,760","10,943",Olmsted,"277,493","18,129"
12,Chippewa,"27,089","22,555",Otter Tail,"110,163","18,996"
13,Chisago,"90,811","16,593",Pennington,"15,424","10,874"
14,Clay,"108,867","17,335",Pine,"35,859","12,310"
15,Clearwater,"9,427","10,698",Pipestone,"19,655","21,399"
16,Cook,"8,966","16,882",Polk,"42,729","13,526"
17,Cottonwood,"21,088","18,544",Pope,"20,459","18,633"
18,Crow Wing,"85,522","13,393",Ramsey,"987,792","18,242"
19,Dakota,"715,290","17,104",Red Lake,"4,078","10,175"
20,Dodge,"37,729","18,331",Redwood,"27,476","17,922"
21,Douglas,"68,086","18,301",Renville,"30,498","20,717"
22,Faribault,"31,294","22,520",Rice,"177,409","26,976"
23,Fillmore,"40,081","19,189",Rock,"19,147","20,341"
24,Freeborn,"63,008","20,641",Roseau,"23,169","14,984"
25,Goodhue,"87,119","18,850",Scott,"230,375","16,068"
26,Grant,"10,310","17,363",Sherburne,"184,952","19,838"
27,Hennepin,"2,292,159","18,553",Sibley,"24,133","16,184"
28,Houston,"21,417","11,476",St. Louis,"383,063","19,145"
29,Hubbard,"20,764","9,953",Stearns,"285,098","18,180"
30,Isanti,"56,067","14,386",Steele,"64,840","17,679"
31,Itasca,"80,265","17,757",Stevens,"20,325","20,774"
32,Jackson,"14,075","14,009",Swift,"18,288","19,433"
33,Kanabec,"16,504","10,312",Todd,"33,013","13,508"
34,Kandiyohi,"85,305","19,997",Traverse,"7,041","21,100"
35,Kittson,"9,969","22,986",Wabasha,"46,421","21,591"
36,Koochiching,"21,647","17,120",Wadena,"33,447","24,510"
37,Lac qui Parle,"13,601","20,081",Waseca,"34,795","18,499"
38,Lake,"19,664","18,605",Washington,"460,537","18,180"
39,Lake of the Woods,"5,957","15,639",Watonwan,"20,172","18,383"
40,Le Sueur,"43,972","15,714",Wilkin,"7,973","12,570"
41,Lincoln,"10,696","18,742",Winona,"106,625","20,970"
42,Lyon,"46,116","17,847",Wright,"194,085","14,621"
43,Mahnomen,"6,643","12,065",Yellow Medicine,"19,972","20,239"
44,Marshall,"10,279","10,944",Unknown/missing,"423,136",

In [30]:
# use iloc to specify order of the columns
df1 = df.iloc[:, 0:3]
df1

0              County Number of Tests Cumulative Rate
1              Aitkin          19,204          12,128
2               Anoka         545,958          15,714
3              Becker          59,238          17,540
4            Beltrami          60,345          13,085
5              Benton   77,865\n9,953          26,976
6           Big Stone          13,220          26,356
7          Blue Earth         136,895          20,641
8               Brown          55,709          22,097
9             Carlton          79,882          22,477
10             Carver         154,305          15,367
11               Cass          31,760          10,943
12           Chippewa          27,089          22,555
13            Chisago          90,811          16,593
14               Clay         108,867          17,335
15         Clearwater           9,427          10,698
16               Cook           8,966          16,882
17         Cottonwood          21,088          18,544
18          Crow Wing          85,522          13,393
19             Dakota         715,290          17,104
20              Dodge          37,729          18,331
21            Douglas          68,086          18,301
22          Faribault          31,294          22,520
23           Fillmore          40,081          19,189
24           Freeborn          63,008          20,641
25            Goodhue          87,119          18,850
26              Grant          10,310          17,363
27           Hennepin       2,292,159          18,553
28            Houston          21,417          11,476
29            Hubbard          20,764           9,953
30             Isanti          56,067          14,386
31             Itasca          80,265          17,757
32            Jackson          14,075          14,009
33            Kanabec          16,504          10,312
34          Kandiyohi          85,305          19,997
35            Kittson           9,969          22,986
36        Koochiching          21,647          17,120
37      Lac qui Parle          13,601          20,081
38               Lake          19,664          18,605
39  Lake of the Woods           5,957          15,639
40           Le Sueur          43,972          15,714
41            Lincoln          10,696          18,742
42               Lyon          46,116          17,847
43           Mahnomen           6,643          12,065
44           Marshall          10,279          10,944

In [31]:
df2 = df.iloc[:, 3:6]
df2

0            County Number of Tests Cumulative Rate
1            Martin          39,876          19,974
2            McLeod          61,300          17,111
3            Meeker          37,736          16,351
4        Mille Lacs          44,688          17,369
5          Morrison          59,179          17,961
6             Mower          79,446          20,061
7            Murray          15,175          18,167
8          Nicollet          66,163          19,585
9            Nobles          30,979          14,185
10           Norman          11,471          17,489
11          Olmsted         277,493          18,129
12       Otter Tail         110,163          18,996
13       Pennington          15,424          10,874
14             Pine          35,859          12,310
15        Pipestone          19,655          21,399
16             Polk          42,729          13,526
17             Pope          20,459          18,633
18           Ramsey         987,792          18,242
19         Red Lake           4,078          10,175
20          Redwood          27,476          17,922
21         Renville          30,498          20,717
22             Rice         177,409          26,976
23             Rock          19,147          20,341
24           Roseau          23,169          14,984
25            Scott         230,375          16,068
26        Sherburne         184,952          19,838
27           Sibley          24,133          16,184
28        St. Louis         383,063          19,145
29          Stearns         285,098          18,180
30           Steele          64,840          17,679
31          Stevens          20,325          20,774
32            Swift          18,288          19,433
33             Todd          33,013          13,508
34         Traverse           7,041          21,100
35          Wabasha          46,421          21,591
36           Wadena          33,447          24,510
37           Waseca          34,795          18,499
38       Washington         460,537          18,180
39         Watonwan          20,172          18,383
40           Wilkin           7,973          12,570
41           Winona         106,625          20,970
42           Wright         194,085          14,621
43  Yellow Medicine          19,972          20,239
44  Unknown/missing         423,136

In [32]:
# removes , from the numbers
df1 = df1.replace(',','', regex=True)
df2 = df2.replace(',','', regex=True)
# alt method

# df1 = df1.replace(',','', regex=True).astype(int)

In [33]:
# this converts the column from str to int
df2[['Number of Tests']] = df2[['Number of Tests']].apply(pd.to_numeric)

In [34]:
# delete off \n9953 that somehow got into the data
df1[['Number of Tests']] = df1[['Number of Tests']].replace('77865\n9953', '77865', regex=False)
df1

0              County Number of Tests Cumulative Rate
1              Aitkin           19204           12128
2               Anoka          545958           15714
3              Becker           59238           17540
4            Beltrami           60345           13085
5              Benton           77865           26976
6           Big Stone           13220           26356
7          Blue Earth          136895           20641
8               Brown           55709           22097
9             Carlton           79882           22477
10             Carver          154305           15367
11               Cass           31760           10943
12           Chippewa           27089           22555
13            Chisago           90811           16593
14               Clay          108867           17335
15         Clearwater            9427           10698
16               Cook            8966           16882
17         Cottonwood           21088           18544
18          Crow Wing           85522           13393
19             Dakota          715290           17104
20              Dodge           37729           18331
21            Douglas           68086           18301
22          Faribault           31294           22520
23           Fillmore           40081           19189
24           Freeborn           63008           20641
25            Goodhue           87119           18850
26              Grant           10310           17363
27           Hennepin         2292159           18553
28            Houston           21417           11476
29            Hubbard           20764            9953
30             Isanti           56067           14386
31             Itasca           80265           17757
32            Jackson           14075           14009
33            Kanabec           16504           10312
34          Kandiyohi           85305           19997
35            Kittson            9969           22986
36        Koochiching           21647           17120
37      Lac qui Parle           13601           20081
38               Lake           19664           18605
39  Lake of the Woods            5957           15639
40           Le Sueur           43972           15714
41            Lincoln           10696           18742
42               Lyon           46116           17847
43           Mahnomen            6643           12065
44           Marshall           10279           10944

In [35]:
df1[['Number of Tests']] = df1[['Number of Tests']].apply(pd.to_numeric)

In [36]:
sum_tests = df1['Number of Tests'] + df2['Number of Tests']
df['Total Number of Tests'] = sum_tests
df

,County,Number of Tests,Cumulative Rate,County,Number of Tests,Cumulative Rate,Total Number of Tests
1,Aitkin,"19,204","12,128",Martin,"39,876","19,974",59080
2,Anoka,"545,958","15,714",McLeod,"61,300","17,111",607258
3,Becker,"59,238","17,540",Meeker,"37,736","16,351",96974
4,Beltrami,"60,345","13,085",Mille Lacs,"44,688","17,369",105033
5,Benton,"77,865\n9,953","26,976",Morrison,"59,179","17,961",137044
6,Big Stone,"13,220","26,356",Mower,"79,446","20,061",92666
7,Blue Earth,"136,895","20,641",Murray,"15,175","18,167",152070
8,Brown,"55,709","22,097",Nicollet,"66,163","19,585",121872
9,Carlton,"79,882","22,477",Nobles,"30,979","14,185",110861
10,Carver,"154,305","15,367",Norman,"11,471","17,489",165776
11,Cass,"31,760","10,943",Olmsted,"277,493","18,129",309253
12,Chippewa,"27,089","22,555",Otter Tail,"110,163","18,996",137252
13,Chisago,"90,811","16,593",Pennington,"15,424","10,874",106235
14,Clay,"108,867","17,335",Pine,"35,859","12,310",144726
15,Clearwater,"9,427","10,698",Pipestone,"19,655","21,399",29082
16,Cook,"8,966","16,882",Polk,"42,729","13,526",51695
17,Cottonwood,"21,088","18,544",Pope,"20,459","18,633",41547
18,Crow Wing,"85,522","13,393",Ramsey,"987,792","18,242",1073314
19,Dakota,"715,290","17,104",Red Lake,"4,078","10,175",719368
20,Dodge,"37,729","18,331",Redwood,"27,476","17,922",65205
21,Douglas,"68,086","18,301",Renville,"30,498","20,717",98584
22,Faribault,"31,294","22,520",Rice,"177,409","26,976",208703
23,Fillmore,"40,081","19,189",Rock,"19,147","20,341",59228
24,Freeborn,"63,008","20,641",Roseau,"23,169","14,984",86177
25,Goodhue,"87,119","18,850",Scott,"230,375","16,068",317494
26,Grant,"10,310","17,363",Sherburne,"184,952","19,838",195262
27,Hennepin,"2,292,159","18,553",Sibley,"24,133","16,184",2316292
28,Houston,"21,417","11,476",St. Louis,"383,063","19,145",404480
29,Hubbard,"20,764","9,953",Stearns,"285,098","18,180",305862
30,Isanti,"56,067","14,386",Steele,"64,840","17,679",120907
31,Itasca,"80,265","17,757",Stevens,"20,325","20,774",100590
32,Jackson,"14,075","14,009",Swift,"18,288","19,433",32363
33,Kanabec,"16,504","10,312",Todd,"33,013","13,508",49517
34,Kandiyohi,"85,305","19,997",Traverse,"7,041","21,100",92346
35,Kittson,"9,969","22,986",Wabasha,"46,421","21,591",56390
36,Koochiching,"21,647","17,120",Wadena,"33,447","24,510",55094
37,Lac qui Parle,"13,601","20,081",Waseca,"34,795","18,499",48396
38,Lake,"19,664","18,605",Washington,"460,537","18,180",480201
39,Lake of the Woods,"5,957","15,639",Watonwan,"20,172","18,383",26129
40,Le Sueur,"43,972","15,714",Wilkin,"7,973","12,570",51945
41,Lincoln,"10,696","18,742",Winona,"106,625","20,970",117321
42,Lyon,"46,116","17,847",Wright,"194,085","14,621",240201
43,Mahnomen,"6,643","12,065",Yellow Medicine,"19,972","20,239",26615
44,Marshall,"10,279","10,944",Unknown/missing,"423,136",,433415

## Theme Parks

Using [2019-Theme-Index-web-1.pdf](2019-Theme-Index-web-1.pdf), save a CSV of the top 10 theme park groups worldwide.

* You can clean the results or you can restrict the area the table is pulled from, up to you

In [37]:
tables = camelot.read_pdf("themepark/2019_parks.pdf", flavor="stream", pages='11')
df = tables[0].df
df

,0,1,2,3,4
0,RANK\n1,GROUP NAME\nWALT DISNEY ATTRACTIONS,% CHANGE\n-0.8%,"ATTENDANCE\n2019\n 155,991,000","ATTENDANCE \n2018\n 157,311,000"
1,2,MERLIN ENTERTAINMENTS GROUP,0.9%,"67,000,000","66,400,000*"
2,3,OCT PARKS CHINA,9.4%,"53,970,000","49,350,000"
3,4,UNIVERSAL PARKS AND RESORTS,2.3%,"51,243,000","50,068,000"
4,5,FANTAWILD GROUP,19.8%,"50,393,000","42,074,000"
5,6,CHIMELONG GROUP,8.9%,"37,018,000","34,007,000"
6,7,SIX FLAGS INC.,2.5%,"32,811,000","32,024,000"
7,8,CEDAR FAIR ENTERTAINMENT COMPANY,7.8%,"27,938,000","25,912,000"
8,9,SEAWORLD PARKS & ENTERTAINMENT,0.2%,"22,624,000","22,582,000"
9,10,PARQUES REUNIDOS,6.2%,"22,195,000","20,900,000"
10,TOP 10 ATTENDANCE GROWTH 2018â€“19,,4.0%,,"521,183,000 501,228,000"
11,Â© 2020 TEA / AECOM,,,,

## Hunting licenses

Using [US_Fish_and_Wildlife_Service_2021.pdf](US_Fish_and_Wildlife_Service_2021.pdf) and [a CSV of state populations](http://goodcsv.com/geography/us-states-territories/), find the states with the highest per-capita hunting license holders.

In [41]:
tables = camelot.read_pdf("fish/wildlife.pdf", flavor="lattice", pages='1')
df = tables[0].df
df

,0,1,2,3,4,5,6,7
0,State,Paid Hunting License \nHolders*,"Resident Hunting Licenses,\nTags, Permits and ...","Non-Resident Hunting \nLicenses,\nTags, Permit...","Total Hunting License, \nTags,Permits & Stamps**","Cost - Resident Hunting \nLicenses,\nTags, Per...","Cost - Non-Resident Hunting \nLicenses,\nTags,...",Gross Cost - Hunting \nLicenses
1,AK,"93,559","423,501","59,235","482,736","$4,859,356","$9,046,715","$13,906,071"
2,AL,"452,400","601,683","45,397","647,080","$9,700,295","$6,715,734","$16,416,029"
3,AR,"343,300","349,098","150,728","499,826","$7,851,601","$11,271,653","$19,123,254"
4,AS,0,0,0,0,$0,$0,$0
5,AZ,"302,383","464,607","88,708","553,315","$13,931,397","$5,968,169","$19,899,566"
6,CA,"262,009","949,540","25,535","975,075","$20,270,941","$1,114,625","$21,385,566"
7,CO,"296,609","481,253","120,954","602,207","$13,270,492","$49,732,815","$63,003,307"
8,CT,"32,052","101,377","4,543","105,920","$1,855,046","$372,108","$2,227,154"
9,DC,0,0,0,0,$0,$0,$0
10,DE,"15,619","45,997","6,044","52,041","$899,857","$499,867","$1,399,724"
11,FL,"191,501","275,295","20,104","295,399","$5,745,815","$1,185,179","$6,930,994"
12,GA,"724,269","1,278,512","156,423","1,434,935","$9,182,934","$9,505,429","$18,688,363"
13,GU,543,"1,334",0,"1,334","$15,995",$0,"$15,995"
14,HI,"10,608","10,697","1,274","11,971","$424,453","$133,770","$558,223"
15,IA,"214,398","567,033","70,562","637,595","$12,654,471","$5,250,727","$17,905,198"
16,ID,"275,244","1,412,039","248,610","1,660,649","$11,465,795","$18,704,191","$30,169,986"
17,IL,"293,617","1,286,280","81,944","1,368,224","$15,058,155","$14,764,600","$29,822,755"
18,IN,"250,481","337,728","21,356","359,084","$8,656,243","$2,450,035","$11,106,278"
19,KS,"264,331","286,196","174,334","460,530","$7,325,503","$18,428,588","$25,754,091"
20,KY,"319,690","432,216","114,649","546,865","$12,223,653","$8,728,198","$20,951,851"
21,LA,"424,918","522,414","52,724","575,138","$7,636,981","$1,958,068","$9,595,049"
22,MA,"55,139","239,101","17,849","256,950","$1,909,776","$445,310","$2,355,086"
23,MD,"116,702","272,730","65,204","337,934","$3,237,325","$3,110,066","$6,347,391"
24,ME,"201,370","193,326","33,866","227,192","$4,443,522","$3,143,929","$7,587,451"
25,MI,"642,242","2,027,911","56,781","2,084,692","$30,975,103","$4,192,335","$35,167,438"
26,MN,"545,300","1,287,146","44,750","1,331,896","$28,262,127","$3,899,420","$32,161,547"
27,MO,"472,993","1,718,224","93,646","1,811,870","$12,049,038","$9,941,978","$21,991,016"
28,MP,23,23,0,23,$230,$0,$230
29,MS,"271,281","292,528","84,168","376,696","$4,729,196","$7,796,435","$12,525,631"
30,MT,"222,309","853,341","186,315","1,039,656","$10,966,890","$26,951,488","$37,918,378"
31,NC,"609,131","280,656","26,404","307,060","$8,274,234","$2,264,888","$10,539,122"
32,ND,"135,724","375,250","126,916","502,166","$4,680,314","$6,094,905","$10,775,219"
33,NE,"180,932","299,496","93,317","392,813","$8,366,685","$7,558,178","$15,924,863"
34,NH,"55,562","129,474","20,511","149,985","$3,071,480","$1,432,078","$4,503,558"
35,NJ,"68,767","281,220","121,963","403,183","$6,328,826","$1,152,802","$7,481,628"
36,NM,"110,874","287,829","112,877","400,706","$5,164,543","$11,689,723","$16,854,266"
37,NV,"89,603","97,387","28,489","125,876","$3,634,268","$3,475,115","$7,109,383"
38,NY,"550,868","1,343,275","49,018","1,392,293","$19,993,113","$4,166,190","$24,159,303"
39,OH,"346,220","770,492","99,530","870,022","$14,636,310","$8,145,996","$22,782,306"
40,OK,"512,724","387,930","27,899","415,829","$5,313,277","$4,704,096","$10,017,373"
41,OR,"328,323","1,250,170","68,043","1,318,213","$22,316,871","$6,004,417","$28,321,288"
42,PA,"945,731","2,299,595","109,096","2,408,691","$31,435,305","$6,418,857","$37,854,162"
43,PR,"7,362","2,151",11,"2,162","$84,926",$760,"$85,686"
44,RI,"7,514","49,019","4,705","53,724","$607,820","$133,965","$741,785"
45,SC,"208,843","893,226","107,735","1,000,961","$4,795,967","$5,180,858","$9,976,825"
46,SD,"213,786","241,059","115,902","356,961","$7,425,329","$13,522,167","$20,947,496"
47,TN,"694,458","722,305","66,774","789,079","$11,501,652","$4,415,002","$15,916,654"
48,TX,"1,094,753","1,617,322","86,692","1,704,014","$34,381,172","$12,097,724","$46,478,896"
49,UT,"250,565","405,303","50,260","455,563","$12,799,520","$6,708,584","$19,508,104"
50,VA,"254,517","776,242","42,686","818,928","$18,589,392","$3,831,438","$22,420,830"
51,VI,0,0,0,0,$0,$0,$0
52,VT,"62,237","166,813","16,988","183,801","$3,083,660","$1,005,616","$4,089,276"
53,WA,"171,940","688,501","13,365","701,866","$16,004,985","$1,063,616","$17,068,601"
54,WI,"666,670","3,965,367","236,639","4,202,006","$28,526,992","$7,884,672","$36,411,664"
55,WV,"205,447","484,447","143,966","628,413","$3,800,948","$4,881,189","$8,682,137"
56,WY,"135,228","186,849","82,865","269,714","$11,254,147","$23,660,065","$34,914,212"
57,Total:,"15,202,669","34,712,508","3,878,354","38,590,862","$545,673,926","$372,804,333","$918,478,259"

In [42]:
# Set the first row as the columns
df.columns = df.loc[0]

In [43]:
# Drop the first row
df = df.drop(0)

In [45]:
df['State'] = df.State.str.strip()

In [47]:
state = pd.read_csv("states.csv")
state['Abbreviation'] = state.Abbreviation.str.strip()
state

,Type,Name,Abbreviation,Capital,Population (2015),Population (2019),area (square miles)
0,State,Alabama,AL,Montgomery,NaN,"4,903,185","52,420"
1,State,Alaska,AK,Juneau,NaN,"731,545","665,384"
2,State,Arizona,AZ,Phoenix,NaN,"7,278,717","113,990"
3,State,Arkansas,AR,Little Rock,NaN,"3,017,804","53,179"
4,State,California,CA,Sacramento,NaN,"39,512,223","163,695"
...,...,...,...,...,...,...,...
60,Territory,Kingman Reef,NaN,NaN,NaN,NaN,0.005
61,Territory,Midway Atoll,NaN,NaN,NaN,NaN,3
62,Territory,Navassa Island,NaN,NaN,NaN,NaN,3
63,Territory,Palmyra Atoll,NaN,NaN,NaN,NaN,1.5
64,Territory,Wake Island,NaN,NaN,NaN,NaN,2.5

In [46]:
combined = df.merge(state, left_on='State', right_on='Abbreviation')
combined

,State,Paid Hunting License \nHolders*,"Resident Hunting Licenses,\nTags, Permits and Stamps","Non-Resident Hunting \nLicenses,\nTags, Permits and Stamps","Total Hunting License, \nTags,Permits & Stamps**","Cost - Resident Hunting \nLicenses,\nTags, Permits and Stamps","Cost - Non-Resident Hunting \nLicenses,\nTags, Permits and Stamps",Gross Cost - Hunting \nLicenses,Type,Name,Abbreviation,Capital,Population (2015),Population (2019),area (square miles)
0,AK,"93,559","423,501","59,235","482,736","$4,859,356","$9,046,715","$13,906,071",State,Alaska,AK,Juneau,NaN,"731,545","665,384"
1,AL,"452,400","601,683","45,397","647,080","$9,700,295","$6,715,734","$16,416,029",State,Alabama,AL,Montgomery,NaN,"4,903,185","52,420"
2,AR,"343,300","349,098","150,728","499,826","$7,851,601","$11,271,653","$19,123,254",State,Arkansas,AR,Little Rock,NaN,"3,017,804","53,179"
3,AS,0,0,0,0,$0,$0,$0,Territory,American Samoa,AS,Pago Pago,"57,400",NaN,581
4,AZ,"302,383","464,607","88,708","553,315","$13,931,397","$5,968,169","$19,899,566",State,Arizona,AZ,Phoenix,NaN,"7,278,717","113,990"
5,CA,"262,009","949,540","25,535","975,075","$20,270,941","$1,114,625","$21,385,566",State,California,CA,Sacramento,NaN,"39,512,223","163,695"
6,CO,"296,609","481,253","120,954","602,207","$13,270,492","$49,732,815","$63,003,307",State,Colorado,CO,Denver,NaN,"5,758,736","104,094"
7,CT,"32,052","101,377","4,543","105,920","$1,855,046","$372,108","$2,227,154",State,Connecticut,CT,Hartford,NaN,"3,565,278","5,543"
8,DC,0,0,0,0,$0,$0,$0,Federal District,District of Columbia,DC,NaN,NaN,"705,749",68
9,DE,"15,619","45,997","6,044","52,041","$899,857","$499,867","$1,399,724",State,Delaware,DE,Dover,NaN,"973,764","2,489"
10,FL,"191,501","275,295","20,104","295,399","$5,745,815","$1,185,179","$6,930,994",State,Florida,FL,Tallahassee,NaN,"21,477,737","65,758"
11,GA,"724,269","1,278,512","156,423","1,434,935","$9,182,934","$9,505,429","$18,688,363",State,Georgia,GA,Atlanta,NaN,"10,617,423","59,425"
12,GU,543,"1,334",0,"1,334","$15,995",$0,"$15,995",Territory,Guam,GU,Hagï¿½tï¿½a,"161,700",NaN,571
13,HI,"10,608","10,697","1,274","11,971","$424,453","$133,770","$558,223",State,Hawaii,HI,Honolulu,NaN,"1,415,872","10,932"
14,IA,"214,398","567,033","70,562","637,595","$12,654,471","$5,250,727","$17,905,198",State,Iowa,IA,Des Moines,NaN,"3,155,070","56,273"
15,ID,"275,244","1,412,039","248,610","1,660,649","$11,465,795","$18,704,191","$30,169,986",State,Idaho,ID,Boise,NaN,"1,787,065","83,569"
16,IL,"293,617","1,286,280","81,944","1,368,224","$15,058,155","$14,764,600","$29,822,755",State,Illinois,IL,Springfield,NaN,"12,671,821","57,914"
17,IN,"250,481","337,728","21,356","359,084","$8,656,243","$2,450,035","$11,106,278",State,Indiana,IN,Indianapolis,NaN,"6,732,219","36,420"
18,KS,"264,331","286,196","174,334","460,530","$7,325,503","$18,428,588","$25,754,091",State,Kansas,KS,Topeka,NaN,"2,913,314","82,278"
19,KY,"319,690","432,216","114,649","546,865","$12,223,653","$8,728,198","$20,951,851",State,Kentucky[E],KY,Frankfort,NaN,"4,467,673","40,408"
20,LA,"424,918","522,414","52,724","575,138","$7,636,981","$1,958,068","$9,595,049",State,Louisiana,LA,Baton Rouge,NaN,"4,648,794","52,378"
21,MA,"55,139","239,101","17,849","256,950","$1,909,776","$445,310","$2,355,086",State,Massachusetts[E],MA,Boston,NaN,"6,892,503","10,554"
22,MD,"116,702","272,730","65,204","337,934","$3,237,325","$3,110,066","$6,347,391",State,Maryland,MD,Annapolis,NaN,"6,045,680","12,406"
23,ME,"201,370","193,326","33,866","227,192","$4,443,522","$3,143,929","$7,587,451",State,Maine,ME,Augusta,NaN,"1,344,212","35,380"
24,MI,"642,242","2,027,911","56,781","2,084,692","$30,975,103","$4,192,335","$35,167,438",State,Michigan,MI,Lansing,NaN,"9,986,857","96,714"
25,MN,"545,300","1,287,146","44,750","1,331,896","$28,262,127","$3,899,420","$32,161,547",State,Minnesota,MN,St. Paul,NaN,"5,639,632","86,936"
26,MO,"472,993","1,718,224","93,646","1,811,870","$12,049,038","$9,941,978","$21,991,016",State,Missouri,MO,Jefferson City,NaN,"6,137,428","69,707"
27,MP,23,23,0,23,$230,$0,$230,Territory,Northern Mariana Islands,MP,Saipan,"52,300",NaN,"1,976"
28,MS,"271,281","292,528","84,168","376,696","$4,729,196","$7,796,435","$12,525,631",State,Mississippi,MS,Jackson,NaN,"2,976,149","48,432"
29,MT,"222,309","853,341","186,315","1,039,656","$10,966,890","$26,951,488","$37,918,378",State,Montana,MT,Helena,NaN,"1,068,778","147,040"
30,NC,"609,131","280,656","26,404","307,060","$8,274,234","$2,264,888","$10,539,122",State,North Carolina,NC,Raleigh,NaN,"10,488,084","53,819"
31,ND,"135,724","375,250","126,916","502,166","$4,680,314","$6,094,905","$10,775,219",State,North Dakota,ND,Bismarck,NaN,"762,062","70,698"
32,NE,"180,932","299,496","93,317","392,813","$8,366,685","$7,558,178","$15,924,863",State,Nebraska,NE,Lincoln,NaN,"1,934,408","77,348"
33,NH,"55,562","129,474","20,511","149,985","$3,071,480","$1,432,078","$4,503,558",State,New Hampshire,NH,Concord,NaN,"1,359,711","9,349"
34,NJ,"68,767","281,220","121,963","403,183","$6,328,826","$1,152,802","$7,481,628",State,New Jersey,NJ,Trenton,NaN,"8,882,190","8,723"
35,NM,"110,874","287,829","112,877","400,706","$5,164,543","$11,689,723","$16,854,266",State,New Mexico,NM,Santa Fe,NaN,"2,096,829","121,590"
36,NV,"89,603","97,387","28,489","125,876","$3,634,268","$3,475,115","$7,109,383",State,Nevada,NV,Carson City,NaN,"3,080,156","110,572"
37,NY,"550,868","1,343,275","49,018","1,392,293","$19,993,113","$4,166,190","$24,159,303",State,New York,NY,Albany,NaN,"19,453,561","54,555"
38,OH,"346,220","770,492","99,530","870,022","$14,636,310","$8,145,996","$22,782,306",State,Ohio,OH,Columbus,NaN,"11,689,100","44,826"
39,OK,"512,724","387,930","27,899","415,829","$5,313,277","$4,704,096","$10,017,373",State,Oklahoma,OK,Oklahoma City,NaN,"3,956,971","69,899"
40,OR,"328,323","1,250,170","68,043","1,318,213","$22,316,871","$6,004,417","$28,321,288",State,Oregon,OR,Salem,NaN,"4,217,737","98,379"
41,PA,"945,731","2,299,595","109,096","2,408,691","$31,435,305","$6,418,857","$37,854,162",State,Pennsylvania[E],PA,Harrisburg,NaN,"12,801,989","46,054"
42,PR,"7,362","2,151",11,"2,162","$84,926",$760,"$85,686",Territory,Puerto Rico,PR,San Juan,NaN,"3,193,694","5,325"
43,RI,"7,514","49,019","4,705","53,724","$607,820","$133,965","$741,785",State,Rhode Island[F],RI,Providence,NaN,"1,059,361","1,545"
44,SC,"208,843","893,226","107,735","1,000,961","$4,795,967","$5,180,858","$9,976,825",State,South Carolina,SC,Columbia,NaN,"5,148,714","32,020"
45,SD,"213,786","241,059","115,902","356,961","$7,425,329","$13,522,167","$20,947,496",State,South Dakota,SD,Pierre,NaN,"884,659","77,116"
46,TN,"694,458","722,305","66,774","789,079","$11,501,652","$4,415,002","$15,916,654",State,Tennessee,TN,Nashville,NaN,"6,829,174","42,144"
47,TX,"1,094,753","1,617,322","86,692","1,704,014","$34,381,172","$12,097,724","$46,478,896",State,Texas,TX,Austin,NaN,"28,995,881","268,596"
48,UT,"250,565","405,303","50,260","455,563","$12,799,520","$6,708,584","$19,508,104",State,Utah,UT,Salt Lake City,NaN,"3,205,958","84,897"
49,VA,"254,517","776,242","42,686","818,928","$18,589,392","$3,831,438","$22,420,830",State,Virginia[E],VA,Richmond,NaN,"8,535,519","42,775"
50,VI,0,0,0,0,$0,$0,$0,Territory,U.S. Virgin Islands,VI,Charlotte Amalie,"103,700",NaN,733
51,VT,"62,237","166,813","16,988","183,801","$3,083,660","$1,005,616","$4,089,276",State,Vermont,VT,Montpelier,NaN,"623,989","9,616"
52,WA,"171,940","688,501","13,365","701,866","$16,004,985","$1,063,616","$17,068,601",State,Washington,WA,Olympia,NaN,"7,614,893","71,298"
53,WI,"666,670","3,965,367","236,639","4,202,006","$28,526,992","$7,884,672","$36,411,664",State,Wisconsin,WI,Madison,NaN,"5,822,434","65,496"
54,WV,"205,447","484,447","143,966","628,413","$3,800,948","$4,881,189","$8,682,137",State,West Virginia,WV,Charleston,NaN,"1,792,147","24,230"
55,WY,"135,228","186,849","82,865","269,714","$11,254,147","$23,660,065","$34,914,212",State,Wyoming,WY,Cheyenne,NaN,"578,759","97,813"

In [52]:
new = combined[['State', 'Name','Population (2019)','Paid Hunting License \nHolders*']]
new

,State,Name,Population (2019),Paid Hunting License \nHolders*
0,AK,Alaska,"731,545","93,559"
1,AL,Alabama,"4,903,185","452,400"
2,AR,Arkansas,"3,017,804","343,300"
3,AS,American Samoa,NaN,0
4,AZ,Arizona,"7,278,717","302,383"
5,CA,California,"39,512,223","262,009"
6,CO,Colorado,"5,758,736","296,609"
7,CT,Connecticut,"3,565,278","32,052"
8,DC,District of Columbia,"705,749",0
9,DE,Delaware,"973,764","15,619"
10,FL,Florida,"21,477,737","191,501"
11,GA,Georgia,"10,617,423","724,269"
12,GU,Guam,NaN,543
13,HI,Hawaii,"1,415,872","10,608"
14,IA,Iowa,"3,155,070","214,398"
15,ID,Idaho,"1,787,065","275,244"
16,IL,Illinois,"12,671,821","293,617"
17,IN,Indiana,"6,732,219","250,481"
18,KS,Kansas,"2,913,314","264,331"
19,KY,Kentucky[E],"4,467,673","319,690"
20,LA,Louisiana,"4,648,794","424,918"
21,MA,Massachusetts[E],"6,892,503","55,139"
22,MD,Maryland,"6,045,680","116,702"
23,ME,Maine,"1,344,212","201,370"
24,MI,Michigan,"9,986,857","642,242"
25,MN,Minnesota,"5,639,632","545,300"
26,MO,Missouri,"6,137,428","472,993"
27,MP,Northern Mariana Islands,NaN,23
28,MS,Mississippi,"2,976,149","271,281"
29,MT,Montana,"1,068,778","222,309"
30,NC,North Carolina,"10,488,084","609,131"
31,ND,North Dakota,"762,062","135,724"
32,NE,Nebraska,"1,934,408","180,932"
33,NH,New Hampshire,"1,359,711","55,562"
34,NJ,New Jersey,"8,882,190","68,767"
35,NM,New Mexico,"2,096,829","110,874"
36,NV,Nevada,"3,080,156","89,603"
37,NY,New York,"19,453,561","550,868"
38,OH,Ohio,"11,689,100","346,220"
39,OK,Oklahoma,"3,956,971","512,724"
40,OR,Oregon,"4,217,737","328,323"
41,PA,Pennsylvania[E],"12,801,989","945,731"
42,PR,Puerto Rico,"3,193,694","7,362"
43,RI,Rhode Island[F],"1,059,361","7,514"
44,SC,South Carolina,"5,148,714","208,843"
45,SD,South Dakota,"884,659","213,786"
46,TN,Tennessee,"6,829,174","694,458"
47,TX,Texas,"28,995,881","1,094,753"
48,UT,Utah,"3,205,958","250,565"
49,VA,Virginia[E],"8,535,519","254,517"
50,VI,U.S. Virgin Islands,NaN,0
51,VT,Vermont,"623,989","62,237"
52,WA,Washington,"7,614,893","171,940"
53,WI,Wisconsin,"5,822,434","666,670"
54,WV,West Virginia,"1,792,147","205,447"
55,WY,Wyoming,"578,759","135,228"

In [57]:
# make columns int
new[['Population (2019)']] = new[['Population (2019)']].replace(',','', regex=True)

/Users/isabellachua/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [60]:
new[['Paid Hunting License \nHolders*']] = new[['Paid Hunting License \nHolders*']].replace(',','', regex=True)

/Users/isabellachua/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [65]:
new[['Population (2019)']] = (new[['Population (2019)']] !='n').astype(int)

/Users/isabellachua/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [66]:
new[['Paid Hunting License \nHolders*']] = (new[['Paid Hunting License \nHolders*']] !='n').astype(int)

In [67]:
# create per capita column
new['per_capita'] = new['Paid Hunting License \nHolders*'] / new['Population (2019)']

<ipython-input-67-930e576403de>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new['per_capita'] = new['Paid Hunting License \nHolders*'] / new['Population (2019)']

In [68]:
new

,State,Name,Population (2019),Paid Hunting License \nHolders*,per_capita
0,AK,Alaska,1,1,1.0
1,AL,Alabama,1,1,1.0
2,AR,Arkansas,1,1,1.0
3,AS,American Samoa,1,1,1.0
4,AZ,Arizona,1,1,1.0
5,CA,California,1,1,1.0
6,CO,Colorado,1,1,1.0
7,CT,Connecticut,1,1,1.0
8,DC,District of Columbia,1,1,1.0
9,DE,Delaware,1,1,1.0
10,FL,Florida,1,1,1.0
11,GA,Georgia,1,1,1.0
12,GU,Guam,1,1,1.0
13,HI,Hawaii,1,1,1.0
14,IA,Iowa,1,1,1.0
15,ID,Idaho,1,1,1.0
16,IL,Illinois,1,1,1.0
17,IN,Indiana,1,1,1.0
18,KS,Kansas,1,1,1.0
19,KY,Kentucky[E],1,1,1.0
20,LA,Louisiana,1,1,1.0
21,MA,Massachusetts[E],1,1,1.0
22,MD,Maryland,1,1,1.0
23,ME,Maine,1,1,1.0
24,MI,Michigan,1,1,1.0
25,MN,Minnesota,1,1,1.0
26,MO,Missouri,1,1,1.0
27,MP,Northern Mariana Islands,1,1,1.0
28,MS,Mississippi,1,1,1.0
29,MT,Montana,1,1,1.0
30,NC,North Carolina,1,1,1.0
31,ND,North Dakota,1,1,1.0
32,NE,Nebraska,1,1,1.0
33,NH,New Hampshire,1,1,1.0
34,NJ,New Jersey,1,1,1.0
35,NM,New Mexico,1,1,1.0
36,NV,Nevada,1,1,1.0
37,NY,New York,1,1,1.0
38,OH,Ohio,1,1,1.0
39,OK,Oklahoma,1,1,1.0
40,OR,Oregon,1,1,1.0
41,PA,Pennsylvania[E],1,1,1.0
42,PR,Puerto Rico,1,1,1.0
43,RI,Rhode Island[F],1,1,1.0
44,SC,South Carolina,1,1,1.0
45,SD,South Dakota,1,1,1.0
46,TN,Tennessee,1,1,1.0
47,TX,Texas,1,1,1.0
48,UT,Utah,1,1,1.0
49,VA,Virginia[E],1,1,1.0
50,VI,U.S. Virgin Islands,1,1,1.0
51,VT,Vermont,1,1,1.0
52,WA,Washington,1,1,1.0
53,WI,Wisconsin,1,1,1.0
54,WV,West Virginia,1,1,1.0
55,WY,Wyoming,1,1,1.0